const ADD_CART_ITEM = "ADD_CART_ITEM";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const CLEAR_CART = "CLEAR_CART";
const MINUS_CART_ITEM = "MINUS_CART_ITEM";

export { ADD_CART_ITEM, REMOVE_CART_ITEM, CLEAR_CART, MINUS_CART_ITEM };