const SET_CART_ITEMS = "SET_CART_ITEMS";
const ADD_CART_ITEM = "ADD_CART_ITEM";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const REMOVE_ALL_CART_ITEM_BY_ID = "REMOVE_ALL_CART_ITEM_BY_ID";

export { ADD_CART_ITEM, SET_CART_ITEMS, REMOVE_CART_ITEM, REMOVE_ALL_CART_ITEM_BY_ID };